services:
  - type: web
    name: after-hours-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn myapp.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: myapp.settings
      - key: SECRET_KEY
        generateValue: true