# Generated by Django 4.2.19 on 2025-04-10 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achievements', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='achievement',
            name='icon',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
    ]
