# Generated by Django 4.2.19 on 2025-04-01 19:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beer', models.IntegerField(default=0, help_text='Number of beers drank (17 ml alcohol per beer)')),
                ('floco', models.IntegerField(default=0, help_text='Number of floco shots (43 ml alcohol per shot)')),
                ('rum', models.IntegerField(default=0, help_text='Number of rum shots (9 ml alcohol per shot)')),
                ('whiskey', models.IntegerField(default=0, help_text='Number of whiskey shots (14 ml alcohol per shot)')),
                ('vodka', models.IntegerField(default=0, help_text='Number of vodka shots (18 ml alcohol per shot)')),
                ('tequila', models.IntegerField(default=0, help_text='Number of tequila shots (23 ml alcohol per shot)')),
                ('shotguns', models.IntegerField(default=0, help_text='Number of shotguns')),
                ('snorkels', models.IntegerField(default=0, help_text='Number of snorkels')),
                ('thrown_up', models.IntegerField(default=0, help_text='Times thrown up')),
                ('xp', models.IntegerField(default=0, help_text='User XP')),
                ('rank', models.CharField(default='Bronze', help_text='User rank', max_length=50)),
                ('friends', models.ManyToManyField(blank=True, to='accounts.profile')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FriendRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accepted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_friend_requests', to='accounts.profile')),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_friend_requests', to='accounts.profile')),
            ],
            options={
                'unique_together': {('from_user', 'to_user')},
            },
        ),
    ]
