# Generated by Django 4.2.19 on 2025-03-04 01:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height', models.FloatField(help_text='Height in centimeters')),
                ('weight', models.FloatField(help_text='Weight in kilograms')),
                ('beer', models.IntegerField(default=0, help_text='Number of beers drank (17 ml alcohol per beer)')),
                ('floco', models.IntegerField(default=0, help_text='Number of floco shots (43 ml alcohol per shot)')),
                ('rum', models.IntegerField(default=0, help_text='Number of rum shots (9 ml alcohol per shot)')),
                ('whiskey', models.IntegerField(default=0, help_text='Number of whiskey shots (14 ml alcohol per shot)')),
                ('vodka', models.IntegerField(default=0, help_text='Number of vodka shots (18 ml alcohol per shot)')),
                ('tequila', models.IntegerField(default=0, help_text='Number of tequila shots (23 ml alcohol per shot)')),
                ('shotguns', models.IntegerField(default=0, help_text='Number of shotguns')),
                ('snorkels', models.IntegerField(default=0, help_text='Number of snorkels')),
                ('thrown_up', models.IntegerField(default=0, help_text='Times thrown up')),
                ('xp', models.IntegerField(default=0, help_text='User XP')),
                ('rank', models.CharField(default='Beginner', help_text='User rank', max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
