# Generated by Django 4.2.19 on 2025-04-04 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='beer',
            field=models.IntegerField(default=0, help_text='Number of Beers/Seltzers drank (17 ml alcohol per beer)'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='floco',
            field=models.IntegerField(default=0, help_text='Number of Flocos (43 ml alcohol per shot)'),
        ),
    ]
