# Generated by Django 4.2.19 on 2025-03-13 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_friendrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='rank',
            field=models.CharField(default='Bronze', help_text='User rank', max_length=50),
        ),
    ]
