# Generated by Django 4.2.19 on 2025-04-06 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_profile_beer_alter_profile_floco'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='display_name',
            field=models.CharField(default='User', help_text='Display name (letters only, max 15 characters)', max_length=15),
        ),
    ]
