# Generated by Django 4.2.19 on 2025-04-10 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_achievement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='display_name',
        ),
        migrations.AddField(
            model_name='profile',
            name='achievements',
            field=models.ManyToManyField(blank=True, related_name='unlocked_by', to='accounts.achievement'),
        ),
    ]
