# Generated by Django 4.2.19 on 2025-04-10 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_userachievement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='achievement',
            name='icon',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='achievements',
        ),
        migrations.AddField(
            model_name='achievement',
            name='points',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='achievement',
            name='profiles',
            field=models.ManyToManyField(blank=True, related_name='achievements', to='accounts.profile'),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.DeleteModel(
            name='UserAchievement',
        ),
    ]
