# Generated by Django 4.2.19 on 2025-04-10 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_remove_achievement_icon_remove_profile_achievements_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Achievement',
        ),
    ]
