# Generated by Django 4.2.19 on 2025-04-11 06:37

import accounts.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_delete_achievement'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=accounts.models.current_log_date, help_text='The day of the log (3 AM to 3 AM)')),
                ('beer', models.PositiveIntegerField(default=0)),
                ('floco', models.PositiveIntegerField(default=0)),
                ('rum', models.PositiveIntegerField(default=0)),
                ('whiskey', models.PositiveIntegerField(default=0)),
                ('vodka', models.PositiveIntegerField(default=0)),
                ('tequila', models.PositiveIntegerField(default=0)),
                ('shotguns', models.PositiveIntegerField(default=0)),
                ('snorkels', models.PositiveIntegerField(default=0)),
                ('thrown_up', models.PositiveIntegerField(default=0)),
                ('xp', models.IntegerField(default=0)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_logs', to='accounts.profile')),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('profile', 'date')},
            },
        ),
    ]
