# Generated by Django 4.2.19 on 2025-04-11 06:47

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_dailylog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailylog',
            name='date',
            field=models.DateField(default=accounts.models.current_log_date, help_text='Log date (3 AM to 3 AM)'),
        ),
    ]
