# Generated by Django 4.2.19 on 2025-04-12 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_dailylog_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='timezone',
            field=models.CharField(default='UTC', help_text="Enter your local timezone (e.g., 'America/New_York')", max_length=50),
        ),
    ]
