# Generated by Django 4.2.19 on 2025-04-12 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_profile_timezone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='timezone',
            field=models.CharField(default='America/Phoenix', help_text="Enter your local timezone (e.g., 'America/New_York')", max_length=50),
        ),
    ]
