# Generated by Django 4.2.19 on 2025-04-23 03:14

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_profile_display_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('start', models.DateTimeField(default=django.utils.timezone.now)),
                ('end', models.DateTimeField()),
                ('goal_beer', models.PositiveIntegerField(blank=True, help_text='Number of beers', null=True)),
                ('goal_floco', models.PositiveIntegerField(blank=True, null=True)),
                ('goal_rum', models.PositiveIntegerField(blank=True, null=True)),
                ('goal_whiskey', models.PositiveIntegerField(blank=True, null=True)),
                ('goal_vodka', models.PositiveIntegerField(blank=True, null=True)),
                ('goal_tequila', models.PositiveIntegerField(blank=True, null=True)),
                ('goal_alc_ml', models.PositiveIntegerField(blank=True, help_text='Total alcohol (ml)', null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_competitions', to='accounts.profile')),
            ],
        ),
        migrations.CreateModel(
            name='CompetitionParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.competition')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.profile')),
            ],
            options={
                'unique_together': {('competition', 'profile')},
            },
        ),
        migrations.AddField(
            model_name='competition',
            name='participants',
            field=models.ManyToManyField(related_name='competitions', through='accounts.CompetitionParticipant', to='accounts.profile'),
        ),
    ]
